<?php

namespace Live\LessonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
  public function findByCreatorOrderedByNameAndLevel($user)
  {

      $qb = $this->createQueryBuilder('l');
      $query = $qb->leftJoin('l.instrument', 'i')
                    ->addSelect('i')
                  ->where($qb->expr()->eq('l.creator', $user->getId()))
                  ->addOrderBy('i.name', 'ASC')
                  ->addOrderBy('i.level', 'ASC')
                  ->getQuery();

      return $query->getResult();
  }
}
